// <auto-generated />
using System;
using CoverMe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoverMe.Migrations
{
    [DbContext(typeof(CoverMeDbContext))]
    [Migration("20191222011149_MakePhoneNumberNullable")]
    partial class MakePhoneNumberNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoverMe.Models.NotificationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<decimal?>("PhoneNumber")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("PhoneNumberCountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RainThreshold")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeToSend")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("NotificationRequests");
                });

            modelBuilder.Entity("CoverMe.Models.SentNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NotificationRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeSent")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SentNotifiations");
                });
#pragma warning restore 612, 618
        }
    }
}
